qtscript: add bbappend with temp fix for SDK
This fixes the following compilation issue while building SDK.

Patch has been borrowed from gentooLTO and authored by Shane Peelar.

 /tmp/ccqctduy.ltrans0.ltrans.o: In function `ctiVMThrowTrampoline':
 <artificial>:(.text+0x4c): undefined reference to `cti_vm_throw'
 collect2: error: ld returned 1 exit status

(cherry picked from commit d4e4a388ebfa91703d7ab13fd91019546c62450d)